task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# local import
from tasks.views import HomeView
from authentication.views import LoginAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('auth/', include('authentication.urls')),
    path('tasks/', include('tasks.urls')),
    path('jwt/login/', LoginAPI.as_view()),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

# local import
from .views import *

urlpatterns = [
    path('filter/<str:category>/', FilterView.as_view(), name= 'filter-task'),
    path('create-task/', TaskCreateView.as_view(), name= 'create-task'),
    path('delete/<int:id>/', TaskDeleteView.as_view(), name= 'delete-task'),
    path('confirm-delete/<int:id>/', TaskDeleteView.as_view(), name= 'confirm-delete-task'),
    path('task-details/<int:pk>/', TaskDetailView.as_view(), name= 'task-details'),
    path('update-task/<int:id>/', TaskUpdateView.as_view(), name= 'update-task'),
    path('delete-image/<int:pk>/', ImageDeleteView.as_view(), name='delete-image'),
    path('delete-image/<int:pk>/', ImageDeleteView.as_view(), name='delete-image-conf'),
    path('search/', TaskSearchView.as_view(), name='task-search'),


    path('api/task/<int:pk>/', TaskAPIView.as_view()),
    path('api/task/', TaskAPIView.as_view(), name='task-api'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.

PRIORITY_CHOICES = (
    ('3', 'High'),
    ('2', 'Medium'),
    ('1', 'Low'),
)

NOTIFICATION_TYPE = (
    ('Start', 'Start'), # start task for send notification
    ('End', 'End'), # end task for send notification
)

class Task(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)
    description = models.TextField(max_length=255, null= True, blank = True)
    priority = models.CharField(max_length = 10, choices = PRIORITY_CHOICES)
    due_date = models.DateField()
    is_completed = models.BooleanField(default = False) 
    is_notified = models.BooleanField(default = False)

    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)


    def __str__(self) -> str:
        return self.title
    
    def get_priority(self):
        '''this function for showing priority in frontend'''
        if self.priority == '3':
            return "High"
        elif self.priority == '2':
            return "Medium"
        else:
            return "Low"

class Image(models.Model):
    task = models.ForeignKey(Task, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/tasks')


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    task = models.ForeignKey(Task, on_delete = models.CASCADE)
    type = models.CharField(max_length = 10, choices = NOTIFICATION_TYPE)
    created_at = models.DateTimeField(auto_now_add = True)

    def __str__(self) -> str:
        return self.task.title
    
    def full_message(self):
        if self.type == 'Start':
            return f"You have started {self.task.title} from today"
        return f"Your due date is over please check the task"

templates/base.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Task Manager</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    
    
    <style>
    .notification {
      /* background-color: #0d6efd; */
      color: white;
      text-decoration: none;
      padding: 3px 6px;
      position: relative;
      display: inline-block;
      border-radius: 2px;
      font-size: 15px;
      background-color: transparent;
    }

    .notification:hover {
      /* background: #0b5ed7; */
      color: #fff;
    }

    .notification .badge {
      position: absolute;
      top: -6px;
      right: -5px;
      padding: 5px 6px;
      border-radius: 50%;
      background: red;
      color: white;
    }

    .notification-section .dropdown-toggle::after {
      content: none;
    }

    .dropdown-toggle::after {
      color: #fff;
    }

    #notifications-dropdown li {
      max-width: 500px;
      word-wrap: break-word;
      display: inline-block;
      white-space: normal;
    }

    #notifications-dropdown.dropdown-menu {
      width: 15rem;
    }
    </style>
  </head>
 
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark my-navbar">
      <div class="container">
        <a class="navbar-brand txt-g fw-bold" href="{% url 'home' %}">TASK MANAGER</a>
        <button class="navbar-toggler bg-black" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
            {% if user.is_authenticated %}
            <li class="nav-item ">
              <a class="nav-link active fw-bold text-white" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active fw-bold text-white" aria-current="page" href="{% url 'create-task' %}">Create Task</a>
            </li> 
            {% endif %}
          </ul>
          {% if user.is_authenticated %}
          <form class="d-flex ms-auto" method="get" action="{% url 'task-search' %}">
            {% csrf_token %}
            <input class="form-control me-2 search-input" type="search" name = "title" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-success txt-white mx-1 btn-sm" type="submit">Search</button>
          </form>
          {% endif %}

            {% if user.is_authenticated %}
             <!-- Notification button -->
              <li class="nav-item dropdown notification-section btn btn-sm">
                <a href="#" class="notification dropdown-toggle" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="true">
                    <span><i class='fa fa-bell'></i></span>
                    <span class="badge" id="notification-badge"></span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="notifications-dropdown"
                data-popper-placement="bottom-end"
                style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(-70px, 42px, 0px);">
                <h3 class="dropdown-item text-center fw-bold">Notifications </h3>
                <!-- <hr class="dropdown-divider"> -->
                  {% if notifications %}
                      {% for notification in notifications %}
                          <hr class="dropdown-divider">
                          <li class="dropdown-item fw-bold">Task name: {{ notification.task.title }}  <small class="fw-normal" style="font-size: 8px;">{{notification.created_at.date}}</small></li>
                          <li class="dropdown-item">{{ notification.full_message }} </li>
                      {% endfor %}
                  {% else %}
                      <li class="dropdown-item" id="no-notifications">No Notifications</li>
                  {% endif %}      
                </ul>
              </li>
              <!-- Notification button end -->

              {% comment %} <a href="{% url '' %}" class="btn btn-primary text-white mx-1 btn-sm">Profile</a>{% endcomment %}
              <a href="{% url 'logout' %}" class="btn btn-danger text-white mx-1 btn-sm">Log Out</a> 

             
            {% else %} 
              <a href="{% url 'signup' %}" class="btn btn-success text-white mx-1 btn-sm">Sign Up</a>
              <a href="{% url 'login' %}" class="btn btn-warning text-white mx-1 btn-sm">Login</a> 
            {% endif %}

        </div>
      </div>
    </nav>
    {% block content %} 
        <div class="content"> 

        </div>
    {% endblock content %}

    <footer class="section-footer border-top">
      <div class="container">
        <section class="footer-bottom border-top row">
          <div class="col-md-2 ">
            <p class="text-white"> &copy 2025 projectferdos </p>
          </div>
          <div class="col-md-8 text-md-center">
            <span  class="px-2">ferdos.khurrom@gmail.com</span>
            <span  class="px-2">+8801844663201</span>
            <span  class="px-2">Feni 3900</span>
          </div>
        </section>
      </div>   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
      
    <script>

        const notificationSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/notification/'
        );

        notificationSocket.onopen = function(event){
          console.log('WebSocket connection open...')
        }
        // notificationSocket.onmessage = function(event) {
        //     const data = JSON.parse(event.data);
        //     //console.log(event);
        //     //console.log(data);
        // document.getElementById("notifications-dropdown").innerHTML = '<li class="dropdown-item fw-bold">Task name: ' + data.task + "</li><li class='dropdown-item'>" + data.msg + "</li><hr class='dropdown-divider'>" + document.getElementById("notifications-dropdown").innerHTML;
        //     document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) ? parseInt(document.getElementById("notification-badge").innerHTML) + 1 : 1;
        // };
        notificationSocket.onmessage = function(event) {
            const data = JSON.parse(event.data);

            const newNotificationItem = document.createElement('li');
            newNotificationItem.classList.add('dropdown-item', 'fw-bold');
            newNotificationItem.innerHTML = 'Task name: ' + data.task;

            const newMessageItem = document.createElement('li');
            newMessageItem.classList.add('dropdown-item');
            newMessageItem.innerText = data.msg;

            const newDivider = document.createElement('hr');
            newDivider.classList.add('dropdown-divider');

            const notificationsContainer = document.getElementById("notifications-dropdown");
            const notificationsHeadline = notificationsContainer.querySelector('.text-center.fw-bold');

            const noNotificationText = document.getElementById("no-notifications");
            if (noNotificationText) {
                noNotificationText.remove();
            }

            notificationsContainer.insertBefore(newDivider, notificationsHeadline.nextSibling);
            notificationsContainer.insertBefore(newMessageItem, notificationsHeadline.nextSibling);
            notificationsContainer.insertBefore(newNotificationItem, notificationsHeadline.nextSibling);


            document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) ? parseInt(document.getElementById("notification-badge").innerHTML) + 1 : 1;
        };

        notificationSocket.onclose = function(event) {
            console.error('WebSocket connection closed unexpectedly', event);
        };

        // click the notification button text = null
        document.getElementById('navbarDropdown').onclick = function(event){
          document.getElementById("notification-badge").innerText = null;
        }
    </script>
    <script> 
      // SHow password function
      function showPassword() {
          var x = document.getElementById("id_password");
          var y = document.getElementById("id_password1");
          var z = document.getElementById("id_password2");
          
          try {
            if (x.type === "password") {
              x.type = "text";
            } else {
              x.type = "password";
            }  
          }
          catch (error){}
          try {
            if (y.type === "password") {
              y.type = "text";
            } else {
              y.type = "password";
            }
          }
          catch (error){}
          try{
            if (z.type === "password") {
              z.type = "text";
            } else {
              z.type = "password";
            }
          }
          catch (error){}          
      }
    </script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %} 

{% if messages %}
{% for m in messages %}
    <div {% if m.tags %} class="{{m.tags}}" {% endif %}><small >{{m}}</small></div>
{% endfor %}
{% endif %}

{% if user.is_authenticated %}

{% if tasks %}
<div class="container ">
    <h1 margin style=" text-align: center;">Task List</h1>
    <div class="row">
        <small class="text-danger ">** Click the task card to get details</small>
        <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                <p class="small mb-0 me-2 text-muted">Filter</p>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="filterDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        All
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="filterDropdown">
                        <li><a class="dropdown-item" href="{% url 'home' %}">All</a></li>
                        <li><a class="dropdown-item" href="{% url 'filter-task' 'completed' %}">Completed</a></li>
                        <li><a class="dropdown-item" href="{% url 'filter-task' 'incompleted' %}">Incompleted</a></li>
                        <li><a class="dropdown-item" href="{% url 'filter-task' 'created' %}">Creation Date</a></li>
                        <li><a class="dropdown-item" href="{% url 'filter-task' 'due_date' %}">Due Date</a></li>
                        <li><a class="dropdown-item" href="{% url 'filter-task' 'priority' %}">Priority</a></li>
                    </ul>
                </div>
            </div>
            {% for task in tasks %}
            <div class="col-md-4 mb-4">
                <a href="{% url 'task-details' task.id %}">
                    <div class="card p-3">
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="badge bg-info">{{ task.get_priority_display }}</span>
                            {% if not task.is_completed %}
                                <span class="badge bg-danger text-dark">Incomplete</span>
                            {% else %}
                                <span class="badge bg-success text-light">Completed</span>
                            {% endif %}
                        </div>
                        <h5 class="mt-3">{{ task.title }}</h5>
                        <p class="text-black-50">{{ task.description }}</p>
                        <div class="d-flex justify-content-between align-items-center mt-3">
                            <span class="badge bg-warning text-dark">Due: {{ task.due_date }}</span>
                            <div>
                                <a href="{% url 'update-task' task.id %}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                                {% comment %} <a href="{% url 'delete-task' task.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a> {% endcomment %}
                                <a href="{% url 'confirm-delete-task' task.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            
            {% endfor %}
        </div>
    </div>
    {% else %}
    <h1 margin style=" text-align: center;"> No Task Available</h1>
    {% endif %}
{% else %}
    <br> <br>
    <h1 margin style=" text-align: center;">Please Log in or Register</h1>
{% endif %}

<div style="margin: 250px"></div>
{% endblock content %}